# syntax=docker/dockerfile:1.2
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: algostats
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NS_MARIADB_USER=user
      - NS_MARIADB_PORT=3306
      - NS_MARIADB_PASSWORD=password
      - NS_MARIADB_HOSTNAME=db
      - NS_MARIADB_DATABASE=algostats
      - MYSQL_URL=mysql://user:password@db:3306/algostats
      - UPDATE_ON_START=true
    container_name: app_container
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
